# ─────────────────────────────────────────────
#  Nginx LOAD BALANCER — round-robin (sirf config)
#  Ye 2 backend ke aage baithta, requests baari-baari baantta.
# ─────────────────────────────────────────────
events {}

http {

    # (1) BACKENDS ka group ("upstream") — inme load baantna hai
    upstream backends {
        server be1:5678;   # BACKEND-1
        server be2:5678;   # BACKEND-2
        # default = ROUND ROBIN (baari-baari). (aur bhi: least_conn, ip_hash...)
    }

    server {
        listen 80;
        location / {
            # (2) request ko upstream-group pe FORWARD karo -> Nginx khud choose karta kaunsa backend
            proxy_pass http://backends;
        }
    }
}
