spring.application.name=orderservice

# port 8081 (payment-service 8082 pe -> do alag service)
server.port=8081

# order-service ka APNA DB (payment ka alag "paydb" -> DB-per-service)
spring.datasource.url=jdbc:h2:mem:orderdb
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Spring Cloud (Feign) compatibility-check OFF -> Boot 4.1 bahut naya, verifier use nahi pehchanta (warna context load fail)
spring.cloud.compatibility-verifier.enabled=false

# ★ CIRCUIT BREAKER config (Resilience4j) — "paymentService" = OrderService ke @CircuitBreaker(name="paymentService") se MATCH.
# sliding-window-size=5        -> pichhli 5 calls ki KHIDKI pe decide karo.
# minimum-number-of-calls=3    -> kam se kam 3 call ho tabhi JUDGE karo (chhote sample pe OPEN mat karo).
# failure-rate-threshold=50    -> in calls me 50%+ FAIL -> CB OPEN.
# wait-duration-in-open-state=10s -> OPEN me 10 sec raho -> phir HALF-OPEN (test-call).
# permitted-number-of-calls-in-half-open-state=2 -> half-open me sirf 2 test-call -> theek? CLOSED : phir OPEN.
resilience4j.circuitbreaker.instances.paymentService.sliding-window-size=5
resilience4j.circuitbreaker.instances.paymentService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.paymentService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.paymentService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.paymentService.permitted-number-of-calls-in-half-open-state=2
