spring.application.name=orderservice

# port 8081 (payment-service 8082 pe -> do alag service)
server.port=8081

# order-service ka APNA DB (payment ka alag "paydb" -> DB-per-service)
spring.datasource.url=jdbc:h2:mem:orderdb
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Spring Cloud (Feign) compatibility-check OFF -> Boot 4.1 bahut naya, verifier use nahi pehchanta (warna context load fail)
spring.cloud.compatibility-verifier.enabled=false
