spring.application.name=paymentservice

# ye service 8082 port pe chalegi (order-service 8081 pe -> do alag service)
server.port=8082

# payment-service ka APNA in-memory H2 DB (order ka alag hoga -> DB-per-service)
spring.datasource.url=jdbc:h2:mem:paydb
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.kafka.bootstrap-servers=localhost:9092
